# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Partitions Lab
email: paul.johnson@sheffield.ac.uk
description: Website for an undergraduate research program on partitions
# baseurl: "/Partitions-Lab" # the subpath of your site, e.g. /blog
url: "https://ptwiddle.github.io/Partitions-Lab" # the base hostname & protocol for your site
twitter_username: ptwiddle
github_username:  ptwiddle

# Build settings
markdown: kramdown
